
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.acme.tshirt_service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-03-05T17:46:17.226-03:00
 * Generated source version: 3.3.2
 *
 */

@javax.jws.WebService(
                      serviceName = "TshirtServicePortTypeService",
                      portName = "TshirtServicePortTypePort",
                      targetNamespace = "http://acme.com/tshirt-service",
                      wsdlLocation = "classpath:wsdl/tshirt-service.wsdl",
                      endpointInterface = "com.acme.tshirt_service.TshirtServicePortType")

public class TshirtServicePortTypePortImpl implements TshirtServicePortType {

    private static final Logger LOG = Logger.getLogger(TshirtServicePortTypePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.acme.tshirt_service.TshirtServicePortType#orderTshirt(com.acme.tshirt_service.OrderTshirt body)*
     */
    public com.acme.tshirt_service.OrderTshirtResponse orderTshirt(OrderTshirt body) throws TshirtFaultException   {
        LOG.info("Executing operation orderTshirt");
        System.out.println(body);
        try {
            com.acme.tshirt_service.OrderTshirtResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TshirtFaultException("TshirtFault_Exception...");
    }

    /* (non-Javadoc)
     * @see com.acme.tshirt_service.TshirtServicePortType#listInventory(com.acme.tshirt_service.ListInventory parameters)*
     */
    public com.acme.tshirt_service.ListInventoryResponse listInventory(ListInventory parameters) throws TshirtFaultException   {
        LOG.info("Executing operation listInventory");
        System.out.println(parameters);
        try {
            com.acme.tshirt_service.ListInventoryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TshirtFaultException("TshirtFault_Exception...");
    }

    /* (non-Javadoc)
     * @see com.acme.tshirt_service.TshirtServicePortType#trackOrder(com.acme.tshirt_service.TrackOrder body)*
     */
    public com.acme.tshirt_service.TrackOrderResponse trackOrder(TrackOrder body) throws TshirtFaultException   {
        LOG.info("Executing operation trackOrder");
        System.out.println(body);
        try {
            com.acme.tshirt_service.TrackOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TshirtFaultException("TshirtFault_Exception...");
    }

}
