package com.acme.tshirt_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-03-30T14:33:56.714-03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://acme.com/tshirt-service", name = "TshirtServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TshirtServicePortType {

    @WebMethod(operationName = "ListInventory", action = "http://acme.com/tshirt-service/list-inventory")
    @WebResult(name = "ListInventoryResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "parameters")
    public ListInventoryResponse listInventory(

        @WebParam(partName = "parameters", name = "ListInventory", targetNamespace = "http://acme.com/tshirt-service")
        ListInventory parameters
    ) throws TshirtFaultException;

    @WebMethod(operationName = "GetCard", action = "http://acme.com/tshirt-service/get-card")
    @WebResult(name = "CreateCard", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public Cards getCard(

        @WebParam(partName = "body", name = "CardId", targetNamespace = "http://acme.com/tshirt-service")
        CardId body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "TrackOrder", action = "http://acme.com/tshirt-service/track-order")
    @WebResult(name = "TrackOrderResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public TrackOrderResponse trackOrder(

        @WebParam(partName = "body", name = "TrackOrder", targetNamespace = "http://acme.com/tshirt-service")
        TrackOrder body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "UpdateCustomer", action = "http://acme.com/tshirt-service/update-customer")
    @WebResult(name = "CustomerId", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public CustomerId updateCustomer(

        @WebParam(partName = "body", name = "UpdateCustomer", targetNamespace = "http://acme.com/tshirt-service")
        Customer body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "GetCustomer", action = "http://acme.com/tshirt-service/get-customer")
    @WebResult(name = "CreateCustomer", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public Customer getCustomer(

        @WebParam(partName = "body", name = "CustomerId", targetNamespace = "http://acme.com/tshirt-service")
        CustomerId body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "OrderTshirt", action = "http://acme.com/tshirt-service/order-tshirt")
    @WebResult(name = "OrderTshirtResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public OrderTshirtResponse orderTshirt(

        @WebParam(partName = "body", name = "OrderTshirt", targetNamespace = "http://acme.com/tshirt-service")
        OrderTshirt body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "CreateCustomer", action = "http://acme.com/tshirt-service/create-customer")
    @WebResult(name = "CustomerId", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public CustomerId createCustomer(

        @WebParam(partName = "body", name = "CreateCustomer", targetNamespace = "http://acme.com/tshirt-service")
        Customer body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "UpdateCard", action = "http://acme.com/tshirt-service/update-card")
    @WebResult(name = "CardId", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public CardId updateCard(

        @WebParam(partName = "body", name = "UpdateCard", targetNamespace = "http://acme.com/tshirt-service")
        Cards body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "CreateCard", action = "http://acme.com/tshirt-service/create-card")
    @WebResult(name = "CardId", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public CardId createCard(

        @WebParam(partName = "body", name = "CreateCard", targetNamespace = "http://acme.com/tshirt-service")
        Cards body
    ) throws TshirtFaultException;
}
