package com.acme.tshirt_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-03-05T17:46:17.255-03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://acme.com/tshirt-service", name = "TshirtServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TshirtServicePortType {

    @WebMethod(operationName = "OrderTshirt", action = "http://acme.com/tshirt-service/order-tshirt")
    @WebResult(name = "OrderTshirtResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public OrderTshirtResponse orderTshirt(

        @WebParam(partName = "body", name = "OrderTshirt", targetNamespace = "http://acme.com/tshirt-service")
        OrderTshirt body
    ) throws TshirtFaultException;

    @WebMethod(operationName = "ListInventory", action = "http://acme.com/tshirt-service/list-inventory")
    @WebResult(name = "ListInventoryResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "parameters")
    public ListInventoryResponse listInventory(

        @WebParam(partName = "parameters", name = "ListInventory", targetNamespace = "http://acme.com/tshirt-service")
        ListInventory parameters
    ) throws TshirtFaultException;

    @WebMethod(operationName = "TrackOrder", action = "http://acme.com/tshirt-service/track-order")
    @WebResult(name = "TrackOrderResponse", targetNamespace = "http://acme.com/tshirt-service", partName = "body")
    public TrackOrderResponse trackOrder(

        @WebParam(partName = "body", name = "TrackOrder", targetNamespace = "http://acme.com/tshirt-service")
        TrackOrder body
    ) throws TshirtFaultException;
}
